apiVersion: apps/v1
kind: Deployment # automatically restarts/starts pods, also spreads out requests into cluster
metadata:
  name: frontend-deployment
spec:
  replicas: 1 # amount of pods
  selector:
    matchLabels: # labels under a different name
      app: frontend-app
  template:  # what should the deployment create
    metadata:
      labels: 
        app: frontend-app
    spec:
      containers:
        - name: nginx
          image: ghcr.io/borbely-dominik-peter/ghaction-k8s-13a-proj-fr:1773433716
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-auth-token
# --- separates, allows multiple things in 1 file
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-certificate
spec:
  secretName: frontend-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - deployment-project-frontend-borbely-dominik-peter.jcloud.jedlik.cloud

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  #annotations # contains a variety of settings, ex.: https-only, whitelist
spec:
  ingressClassName: nginx #needed?
  tls:
    - hosts:
        - deployment-project-frontend-borbely-dominik-peter.jcloud.jedlik.cloud
      secretName: frontend-certificate
  rules:
    - host: deployment-frontend-borbelydominikpeter.jcloud.jedlik.cloud # url of pod
      http:
        paths: # distributes subpaths to different pods
          - path: /
            pathType: Prefix
            backend: # backend pod
              service: # type of ...
                name: nginx-cluster-ip-service
                port:
                  number: 80 # targetport

# command to execute: kubectl apply -f <FILENAME/.>
# to check if it works: kubectl get <pod/service>, kubectl describe pod <PODNAME>, kubectl logs <PODNAME>, kubectl cluster-info
# to delete: kubectl delete -f <FILENAME/.>