GET http://localhost:8000/api/country/France
Accept: application/json
Content-Type: application/json

####

GET http://localhost:9999
Accept: application/json
Content-Type: application/json

####


GET http://laravel-deploymentproj-borbelydominikpeter.jcloud.jedlik.cloud/api/country/Korea
Accept: application/json
Content-Type: application/json


#### 

GET http://nginx-test-borbelydominikpeter.jcloud.jedlik.cloud/
Accept: application/json
Content-Type: application/json